using System.Text.Json;
using Shiny.SqliteDocumentDb.Tests.Fixtures;
using Xunit;

namespace Shiny.SqliteDocumentDb.Tests;

public class IdAutoGenerationTests : IDisposable
{
    readonly SqliteDocumentStore store;
    static readonly TestJsonContext ctx = new(new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

    public IdAutoGenerationTests()
    {
        this.store = new SqliteDocumentStore(new DocumentStoreOptions
        {
            ConnectionString = "Data Source=:memory:",
            JsonSerializerOptions = ctx.Options
        });
    }

    public void Dispose() => this.store.Dispose();

    // ── Guid auto-generation ────────────────────────────────────────

    [Fact]
    public async Task GuidId_AutoGenerated_WhenDefault()
    {
        var model = new GuidIdModel { Name = "Test" };
        Assert.Equal(Guid.Empty, model.Id);

        await this.store.Insert(model, ctx.GuidIdModel);

        Assert.NotEqual(Guid.Empty, model.Id);
    }

    [Fact]
    public async Task GuidId_Preserved_WhenExplicit()
    {
        var explicitId = Guid.NewGuid();
        var model = new GuidIdModel { Id = explicitId, Name = "Explicit" };

        await this.store.Insert(model, ctx.GuidIdModel);

        Assert.Equal(explicitId, model.Id);

        var result = await this.store.Get<GuidIdModel>(explicitId, ctx.GuidIdModel);
        Assert.NotNull(result);
        Assert.Equal("Explicit", result.Name);
        Assert.Equal(explicitId, result.Id);
    }

    // ── String auto-generation ──────────────────────────────────────

    [Fact]
    public async Task StringId_Throws_WhenEmpty()
    {
        var model = new StringIdModel { Name = "Test" };
        Assert.Equal("", model.Id);

        await Assert.ThrowsAsync<InvalidOperationException>(
            () => this.store.Insert(model, ctx.StringIdModel));
    }

    [Fact]
    public async Task StringId_Throws_WhenNull()
    {
        var model = new StringIdModel { Id = null!, Name = "Test" };

        await Assert.ThrowsAsync<InvalidOperationException>(
            () => this.store.Insert(model, ctx.StringIdModel));
    }

    [Fact]
    public async Task StringId_Preserved_WhenExplicit()
    {
        var model = new StringIdModel { Id = "my-custom-id", Name = "Explicit" };

        await this.store.Insert(model, ctx.StringIdModel);

        Assert.Equal("my-custom-id", model.Id);

        var result = await this.store.Get<StringIdModel>("my-custom-id", ctx.StringIdModel);
        Assert.NotNull(result);
        Assert.Equal("Explicit", result.Name);
    }

    // ── Int auto-generation ─────────────────────────────────────────

    [Fact]
    public async Task IntId_AutoGenerated_WhenZero()
    {
        var model = new IntIdModel { Name = "First" };
        Assert.Equal(0, model.Id);

        await this.store.Insert(model, ctx.IntIdModel);

        Assert.Equal(1, model.Id);
    }

    [Fact]
    public async Task IntId_AutoIncrement()
    {
        var m1 = new IntIdModel { Name = "First" };
        var m2 = new IntIdModel { Name = "Second" };
        var m3 = new IntIdModel { Name = "Third" };

        await this.store.Insert(m1, ctx.IntIdModel);
        await this.store.Insert(m2, ctx.IntIdModel);
        await this.store.Insert(m3, ctx.IntIdModel);

        Assert.Equal(1, m1.Id);
        Assert.Equal(2, m2.Id);
        Assert.Equal(3, m3.Id);
    }

    [Fact]
    public async Task IntId_Preserved_WhenExplicit()
    {
        var model = new IntIdModel { Id = 42, Name = "Explicit" };

        await this.store.Insert(model, ctx.IntIdModel);

        Assert.Equal(42, model.Id);

        var result = await this.store.Get<IntIdModel>(42, ctx.IntIdModel);
        Assert.NotNull(result);
        Assert.Equal("Explicit", result.Name);
        Assert.Equal(42, result.Id);
    }

    // ── Long auto-generation ────────────────────────────────────────

    [Fact]
    public async Task LongId_AutoGenerated_WhenZero()
    {
        var model = new LongIdModel { Name = "First" };
        Assert.Equal(0L, model.Id);

        await this.store.Insert(model, ctx.LongIdModel);

        Assert.Equal(1L, model.Id);
    }

    [Fact]
    public async Task LongId_AutoIncrement()
    {
        var m1 = new LongIdModel { Name = "First" };
        var m2 = new LongIdModel { Name = "Second" };

        await this.store.Insert(m1, ctx.LongIdModel);
        await this.store.Insert(m2, ctx.LongIdModel);

        Assert.Equal(1L, m1.Id);
        Assert.Equal(2L, m2.Id);
    }

    [Fact]
    public async Task LongId_Preserved_WhenExplicit()
    {
        var model = new LongIdModel { Id = 999L, Name = "Explicit" };

        await this.store.Insert(model, ctx.LongIdModel);

        Assert.Equal(999L, model.Id);

        var result = await this.store.Get<LongIdModel>(999L, ctx.LongIdModel);
        Assert.NotNull(result);
        Assert.Equal("Explicit", result.Name);
    }

    // ── Int/Long auto-increment scoped per TypeName ─────────────────

    [Fact]
    public async Task AutoIncrement_ScopedPerType()
    {
        var intModel = new IntIdModel { Name = "Int" };
        var longModel = new LongIdModel { Name = "Long" };

        await this.store.Insert(intModel, ctx.IntIdModel);
        await this.store.Insert(longModel, ctx.LongIdModel);

        // Both should start at 1 since they are different TypeNames
        Assert.Equal(1, intModel.Id);
        Assert.Equal(1L, longModel.Id);
    }

    // ── Type without Id throws ──────────────────────────────────────

    [Fact]
    public async Task NoIdProperty_Throws()
    {
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => this.store.Insert(new NoIdModel { Name = "Test" }));

        Assert.Contains("Id", ex.Message);
    }

    // ── Type with wrong Id type (decimal) throws ────────────────────

    [Fact]
    public async Task BadIdType_Throws()
    {
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => this.store.Insert(new BadIdTypeModel { Name = "Test" }));

        Assert.Contains("unsupported type", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    // ── Round-trip: Set → query ToList → Id is populated on result ──

    [Fact]
    public async Task RoundTrip_QueryReturnsIdOnResult()
    {
        var user = new User { Id = "alice-1", Name = "Alice", Age = 25 };
        await this.store.Insert(user, ctx.User);

        var results = await this.store.Query(ctx.User).ToList();

        Assert.Single(results);
        Assert.Equal(user.Id, results[0].Id);
        Assert.False(string.IsNullOrEmpty(results[0].Id));
        Assert.Equal("Alice", results[0].Name);
    }

    [Fact]
    public async Task RoundTrip_GetReturnsIdOnResult()
    {
        var user = new User { Id = "explicit-id", Name = "Bob", Age = 30 };
        await this.store.Insert(user, ctx.User);

        var result = await this.store.Get<User>("explicit-id", ctx.User);

        Assert.NotNull(result);
        Assert.Equal("explicit-id", result.Id);
        Assert.Equal("Bob", result.Name);
    }

    // ── Upsert with default Id throws ───────────────────────────────

    [Fact]
    public async Task Upsert_WithDefaultId_Throws()
    {
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => this.store.Upsert(new User { Name = "Test" }, ctx.User));

        Assert.Contains("non-default Id", ex.Message);
    }

    // ── Upsert with explicit Id works ───────────────────────────────

    [Fact]
    public async Task Upsert_WithExplicitId_Works()
    {
        await this.store.Insert(new User { Id = "u1", Name = "Allan", Age = 30, Email = "allan@test.com" }, ctx.User);

        await this.store.Upsert(new User { Id = "u1", Name = "Allan", Age = 31 }, ctx.User);

        var result = await this.store.Get<User>("u1", ctx.User);
        Assert.NotNull(result);
        Assert.Equal(31, result.Age);
        Assert.Equal("allan@test.com", result.Email);
    }
}
